# Basic info
name: Silvere Heraudeau
title: Silvere Heraudeau
email: silvere.heraudeau@gmail.com
description: 
  en: My personal website
  fr: Mon site personnel
disclaimer:
  en: "Disclaimer: This site is currently in construction. As such, almost no styles are present. I am currently working on a design."
  fr: "Avertissement : Ce site est actuellement en construction. C'est pourquoi il n'y a presque pas de styles. Je suis en train de travailler sur une apparence visuelle."
lang: en
languages: ["en", "fr"]
permalink: /:categories/:collection/:title/

# Base URL is used in the manner that is specified by this guide
# (http://jekyllrb.com/docs/github-pages/) which is to say, it's
# not used at all.
baseurl: ""
url: "https://silvereh.github.io"
github_username: silvereh

# Languages and syntax highlighting
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Include static pages
include: ["_content"]

exclude: [
  "_assets",
  "Gemfile",
  "Gemfile.lock",
  "gulpfile.js",
  "node_modules",
  "package.json"
]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Silvere Heraudeau"
      comments: true
  - scope:
      path: ""
    values:
      layout: "default"
      author: "Silvere Heraudeau"

theme: null
